<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->truncate(); //for cleaning earlier data to avoid duplicate entries
        DB::table('users')->insert([
          'name' => 'Luminos',
          'email' => 'adminposterios1@gmail.com',
          'password' => Hash::make('admin123'),
          'gender' => 'Male',
          'dob' => '2022-06-15',
          'role' => 'Admin',
          'grade' => 10,
          'sekolah' => 'Posterios School',
          'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'status' => 'Approved',
          'email_verified_at' => '2022-06-11 04:20:56',
          'created_at' => '2022-06-15 04:20:56',
          'updated_at' => '2022-06-15 04:20:56',
        ]);
        DB::table('users')->insert([
            'name' => 'Admin Posterios 1',
            'email' => 'adminposterios1@gmail.com',
            'password' => Hash::make('admin123'),
            'gender' => 'Male',
            'dob' => '2022-06-15',
            'role' => 'Admin',
            'grade' => 10,
            'sekolah' => 'Posterios School',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-06-11 04:20:56',
            'created_at' => '2022-06-15 04:20:56',
            'updated_at' => '2022-06-15 04:20:56',
          ]);
        DB::table('users')->insert([
          'name' => 'Admin Posterios 2',
          'email' => 'adminposterios2@gmail.com',
          'password' => Hash::make('admin123'),
          'gender' => 'Male',
          'dob' => '2022-06-15',
          'role' => 'Admin',
          'grade' => 10,
          'sekolah' => 'Posterios School',
          'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'status' => 'Approved',
          'email_verified_at' => '2022-06-15 04:21:42',
          'created_at' => '2022-06-15 04:21:42',
          'updated_at' => '2022-06-15 04:21:42',
        ]);
        DB::table('users')->insert([
          'name' => 'Admin Posterios 3',
          'email' => 'adminposterios3@gmail.com',
          'password' => Hash::make('admin123'),
          'gender' => 'Male',
          'dob' => '2022-06-15',
          'role' => 'Admin',
          'grade' => 10,
          'sekolah' => 'Posterios School',
          'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
          'status' => 'Approved',
          'email_verified_at' => '2022-06-15 04:22:33',
          'created_at' => '2022-06-15 04:22:33',
          'updated_at' => '2022-06-15 04:22:33',
        ]);
        DB::table('users')->insert([
            'name' => 'Mr. Hallend',
            'email' => 'hallend@gmail.com',
            'password' => Hash::make('hallend123'),
            'gender' => 'Male',
            'dob' => '1988-04-19',
            'role' => 'Teacher',
            'grade' => 10,
            'sekolah' => 'SMK TKJ Pekanbaru',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-06-15 04:20:17',
            'created_at' => '2022-06-15 04:20:17',
            'updated_at' => '2022-06-15 04:20:17',
          ]);
        DB::table('users')->insert([
            'name' => 'Mr. M. Yazid ',
            'email' => 'yazid0192@gmail.com',
            'password' => Hash::make('yazid123'),
            'gender' => 'Male',
            'dob' => '2000-03-25',
            'role' => 'Teacher',
            'grade' => 11,
            'sekolah' => 'SMAN 2 Jakarta',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-06-15 04:28:11',
            'created_at' => '2022-06-15 03:28:11',
            'updated_at' => '2022-06-15 03:28:11',
          ]);
        DB::table('users')->insert([
            'name' => 'Adi Darmawan ',
            'email' => 'darmanawan22@gmail.com',
            'password' => Hash::make('darmawan123'),
            'gender' => 'Male',
            'dob' => '2007-04-14',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAN 2 Jakarta',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-06-15 03:19:32',
            'created_at' => '2022-06-16 03:20:24',
            'updated_at' => '2022-06-15 03:20:24',
          ]);
          DB::table('users')->insert([
            'name' => 'Joseph laia',
            'email' => 'jlaia11@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2005-02-11',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMA Tarsisius 2',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 04:19:32',
            'created_at' => '2022-04-16 04:19:32',
            'updated_at' => '2022-04-18 04:19:32',
          ]);

          DB::table('users')->insert([
            'name' => 'Dessy natalia',
            'email' => 'dessnat21@gmail.com',
            'password' => Hash::make('DessyNat21'),
            'gender' => 'Female',
            'dob' => '2005-05-21',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:23:32',
            'created_at' => '2022-04-18 08:23:32',
            'updated_at' => '2022-04-18 08:23:32',
          ]);

          DB::table('users')->insert([
            'name' => 'Nicho siagian',
            'email' => 'nico_siagian23@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2005-04-23',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:24:32',
            'created_at' => '2022-04-18 08:24:22',
            'updated_at' => '2022-04-18 08:24:22',
          ]);

          DB::table('users')->insert([
            'name' => 'Albert Yunus',
            'email' => 'alyun@gmail.com',
            'password' => Hash::make('yunusAlbert2'),
            'gender' => 'Male',
            'dob' => '2004-04-15',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:24:35',
            'created_at' => '2022-04-18 08:24:35',
            'updated_at' => '2022-04-18 08:24:35',
          ]);

          DB::table('users')->insert([
            'name' => 'Amelya gressya',
            'email' => 'age_gracia28@gmail.com',
            'password' => Hash::make('Agressya21'),
            'gender' => 'Female',
            'dob' => '2005-09-28',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:26:30',
            'created_at' => '2022-04-18 08:26:30',
            'updated_at' => '2022-04-18 08:26:30',
          ]);

          DB::table('users')->insert([
            'name' => 'Yuliana',
            'email' => 'yuliana21@gmail.com',
            'password' => Hash::make('qwert123'),
            'gender' => 'Female',
            'dob' => '2004-07-21',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:27:03',
            'created_at' => '2022-04-18 08:27:03',
            'updated_at' => '2022-04-18 08:27:03',
          ]);

          DB::table('users')->insert([
            'name' => 'Febry lomboan',
            'email' => 'febrylomboan007@gmail.com',
            'password' => Hash::make('1234567'),
            'gender' => 'Male',
            'dob' => '2005-02-07',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:27:42',
            'created_at' => '2022-04-18 08:27:42',
            'updated_at' => '2022-04-18 08:27:42',
          ]);

          DB::table('users')->insert([
            'name' => 'jeremi',
            'email' => 'jeremi29@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2005-06-29',
            'role' => 'Student',
            'grade' => 12,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Andrew Kus',
            'email' => 'andrew.m@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-08-05',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'jose',
            'email' => 'jose.j@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-08-05',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK Bethel',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'kalvin eff',
            'email' => 'effendi.kalvin@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-08-05',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Alexander Gun.',
            'email' => 'AlexanderG12@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-05-28',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]); // 13
          DB::table('users')->insert([
            'name' => 'Mikayla Q.',
            'email' => 'mikaela23@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-01-18',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Clea C',
            'email' => 'cleaclarissa26@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-10-26',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Sella D',
            'email' => 'sella123@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-04-19',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Adrian S',
            'email' => 'ad.rian06@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-11-06',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Albert Ry',
            'email' => 'aryns.ll@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-08-24',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Ribka',
            'email' => 'ribkahu.ta125@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-12-05',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Excel K',
            'email' => 'excelkennet@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-03-17',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]); // 20
          DB::table('users')->insert([
            'name' => 'Bryan S',
            'email' => 'bryanss10@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-10-08',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Julian A',
            'email' => 'abel.sug055@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-11-25',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Matthew L',
            'email' => 'matthew.lee@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-04-12',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'michael simulia',
            'email' => 'michael.simulya@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-02-11',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Stephanie L',
            'email' => 'laurensia33@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-09-15',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'natasha',
            'email' => 'nathasasa@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-12-04',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Daud R',
            'email' => 'raja.daud55@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-05-23',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Willy K',
            'email' => 'kusnadi.w@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-07-23',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Roland R',
            'email' => 'roland.ramos22@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-12-22',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Vanessa Putri',
            'email' => 'vanvan.p@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-03-07',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]); // 30




          DB::table('users')->insert([
            'name' => 'Audrey',
            'email' => 'alexaudrey@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-03-16',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'ray richie',
            'email' => 'richie.rr@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-02-25',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Sebastian',
            'email' => 'sebastian0125@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-01-25',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Melissa Ivana',
            'email' => 'sasaivana@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-08-02',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Gisella Olivia',
            'email' => 'go.oliv@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-06-27',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Grace L',
            'email' => 'gracegrace@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-04-30',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Daniel',
            'email' => 'daniel.s@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-09-13',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Felicia W',
            'email' => 'felicia.cie@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-06-22',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Christian D',
            'email' => 'christian@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-02-09',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'jason',
            'email' => 'jasonicho31@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-03-31',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]); // 40






          DB::table('users')->insert([
            'name' => 'Ruth',
            'email' => 'ruthruth@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-07-26',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'alvin sud',
            'email' => 'sudino.alvinalvin@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-09-16',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'joshua siregar',
            'email' => 'joshua.siregar@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Male',
            'dob' => '2006-01-13',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'Evelyn',
            'email' => 'eve.lyn@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-06-05',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);
          DB::table('users')->insert([
            'name' => 'indriana wijaya',
            'email' => 'indriana.w@gmail.com',
            'password' => Hash::make('qwerty123'),
            'gender' => 'Female',
            'dob' => '2006-05-02',
            'role' => 'Student',
            'grade' => 11,
            'sekolah' => 'SMAK HI',
            'image_selfie' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'image_card' => 'images/user/YYGqnBlj0GBLAEo2WgLcDJfOO93S132ruqXg0KSv.jpg',
            'status' => 'Approved',
            'email_verified_at' => '2022-04-18 08:28:10',
            'created_at' => '2022-04-18 08:28:10',
            'updated_at' => '2022-04-18 08:28:10',
          ]);



    }
}
